<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <style>
     
        textarea{
            resize: none;
        }
    </style>
</head>

<body class="container-fluid">
    <h1>Привет, мир! <?php echo $_SESSION["user"]["name"] ."  " .$_SESSION["user"]["surname"]?></h1>
        <ul>
        <li><a href="/">Главная</a></li>
        <li><a href="/views/admin">Админ</a></li>
            <li><a href="/views/adminorders">Заказы</a></li>
            <li><a href="/views/adminusers">Пользователи</a></li>
            <li><a href="/views/adminlogs">Логи</a></li>
    </ul>


    <table class="table table-responsive users-table">
        <thead>
            <tr>
                <td>
                    Название
                </td>
                <td>
                    Картинка
                </td>
                <td>
                    Цена
                </td>
                <td>
                    Описание
                </td>

            </tr>
        </thead>

    </table>
<?php
//$allproduct =$qerybuilder->all("product");
foreach($allproduct as $data){
?>



    <form method="POST" action="/views/admin/updateDelete_product" enctype="multipart/form-data">
        <table class="table table-responsive users-table">

            <tbody>
                <tr>
                    <td>
                            <input type="hidden" type="text" name="id" value="<?php echo (int)$data["id"];?>" >
                        <input class="form-control" name="nameProduct" type="text"   value="<?php echo $data["name"];?>">
                    </td>
                    <td>
                    <img class="img-fluid" src="<?php echo $data["minpath"];?>" width="100" height="100" alt=""><input type="file" class="form-control-file"  style="float:right;" name="imgFile" id="exampleFormControlFile1" >
                    </td>
                    <td>
                        <input class="form-control" name="price" type="number" placeholder="price"  value="<?php echo (int)$data["price"];?>">
                    </td>
                    <td>

                        <textarea class="form-control" id="exampleFormControlTextarea1" name="textProduct"  rows="3" ><?php echo $data["description"];?></textarea>
                    </td>

                    <td>
                        <button type="submit" name="deleteProduct" class="btn btn-danger create-button">Удалить</button> <br><br>
                       
                        <button type="submit" name="updateProduct" class="btn btn-success create-button">Изменить</button> 
                    </td>
                   
                </tr>
            </tbody>
        </table>

    </form>
    <?php 
}
    
    ?>
    <form  method="POST" action="/views/admin/add_product" enctype="multipart/form-data">
        <table class="table table-responsive users-table">

            <tbody>
                <tr>
                    <td>
                      
                        <input class="form-control" name="nameProduct" type="text" placeholder="admin" data-validate="required" value="fdsfsdfsdf" required>
                    </td>
                    <td>

                        <input type="file" class="form-control-file" name="imgFile" id="exampleFormControlFile1" data-validate="required" required>
                    </td>
                    <td>
                        <input class="form-control" name="price" type="number" placeholder="price" data-validate="required" value="12312312" required>
                    </td>
                    <td>

                        <textarea class="form-control" id="exampleFormControlTextarea1" name="textProduct" data-validate="required" required rows="3"></textarea>
                    </td>

                    <td>

                        <button type="submit" name="createProduct" class="btn btn-success create-button">Создать</button>
                    </td>
                    
                </tr>
            </tbody>
        </table>

    </form>
    <script>
    </script>
</body>

</html>
